spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wxshop?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml
